
import type { AppData } from "@/lib/types"

export const initialData: AppData = {
  cafeCategories: [
    { id: "combos", title: "Combos", icon: "Utensils" },
    { id: "coffee", title: "Coffee", icon: "Coffee" },
    { id: "not-coffee", title: "Not Coffee" },
    { id: "food", title: "The Food", icon: "Utensils" },
    { id: "goods", title: "The Goods", icon: "Gift" },
    { id: "merch", title: "Merch", icon: "ShoppingBag" },
    { id: "catering", title: "Catering", icon: "Utensils" },
    { id: "bouquets", title: "Bouquets & Strawberries", icon: "Gift" },
  ],
  cafeItems: [
    {
      id: "combos-0",
      categoryId: "combos",
      name: "Morning Boost",
      price: "7.50",
      description:
        "Coffee paired with a Bagel Sandwich for a perfect start to your day (save 1.15).",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "combos-1",
      categoryId: "combos",
      name: "Sweet Treat",
      price: "7.50",
      description:
        "Indulgent Mocha with a fresh Brownie for a rich, comforting escape (save 0.85).",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },

    {
      id: "coffee-0",
      categoryId: "coffee",
      name: "Frappe",
      price: "5.55",
      description:
        "A velvety iced latte blended to creamy perfection with our in-house roast, topped with luscious Sweet Beans whipped cream or cold foam. Pair with a Muffin for +3.00.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-1",
      categoryId: "coffee",
      name: "Mocha",
      price: "5.25",
      description:
        "Indulgent mocha crafted with our legendary in-house chocolate sauce for a rich, comforting escape.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-2",
      categoryId: "coffee",
      name: "Latte",
      price: "5.00",
      description:
        "A luxurious assortment of flavors in our specialty lattes, made with our own velvety in-house syrups and sauces (Small 4.50 / Medium 5.00 / Large 5.50).",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-3",
      categoryId: "coffee",
      name: "Cappuccino",
      price: "4.90",
      description:
        "Traditional Italian-style cappuccino with our in-house roast and expertly steamed milk and foam for a bold, frothy delight.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-4",
      categoryId: "coffee",
      name: "Cold Brew",
      price: "4.85",
      description:
        "Our in-house roast steeped for 24 hours to deliver a smooth, bold flavor that's refreshingly invigorating.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-5",
      categoryId: "coffee",
      name: "Americano",
      price: "4.50",
      description:
        "Robust traditional Americano with 3 shots of espresso and equal parts water for an intense coffee experience.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-6",
      categoryId: "coffee",
      name: "Coffee Traveler",
      price: "19.50",
      description:
        "Convenient 96 oz. box of freshly brewed coffee from our amazing in-house roast blend.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-7",
      categoryId: "coffee",
      name: "Coffee",
      price: "3.15",
      description:
        "Freshly brewed coffee from our amazing in-house roast blend, smooth and aromatic.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "coffee-8",
      categoryId: "coffee",
      name: "Espresso Cup",
      price: "2.25",
      description:
        "Pure perfection: our espresso roast straight to the cup, intense and satisfying.",
      page: "cafe",
      subpage: "menu",
    },

    {
      id: "not-coffee-0",
      categoryId: "not-coffee",
      name: "Chai Tea Latte",
      price: "6.50",
      description:
        "Lovely chilled spiced vanilla chai whipped with steamed milk, then poured over ice for a creamy, exotic treat.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-1",
      categoryId: "not-coffee",
      name: "Red Bull Italian Ice",
      price: "6.50",
      description:
        "Energizing blend of our in-house raspberry syrup with 8oz of Red Bull and heavy cream for a bold, creamy boost.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-2",
      categoryId: "not-coffee",
      name: "Fruit Smoothie",
      price: "6.50",
      description:
        "Vibrant smoothie made with real fresh-cut in-house fruit for a refreshing, natural burst of flavor.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-3",
      categoryId: "not-coffee",
      name: "Frozen Hot Chocolate",
      price: "5.00",
      description:
        "Our famous hot chocolate blended into a cool, creamy iced classic that's irresistibly indulgent.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-4",
      categoryId: "not-coffee",
      name: "Fruit Bomb",
      price: "5.00",
      description:
        "Fantastic blend of fruit and soda mixed into a refreshing flavor explosion.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-5",
      categoryId: "not-coffee",
      name: "London Fog",
      price: "4.20",
      description:
        "Your choice of tea steeped in perfectly steamed milk for a full, creamy taste that's soothing and elegant.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-6",
      categoryId: "not-coffee",
      name: "Hot Chocolate",
      price: "4.00",
      description:
        "Great hot chocolate made with our legendary in-house chocolate sauce, perfect for the whole family.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-7",
      categoryId: "not-coffee",
      name: "Steamer",
      price: "3.30",
      description:
        "Any of our specialty flavors in steamed milk without espresso, warm and comforting.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-8",
      categoryId: "not-coffee",
      name: "Tea",
      price: "2.80",
      description:
        "Choose from our great tea options, from regular black to vibrant watermelon hibiscus.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-9",
      categoryId: "not-coffee",
      name: "Soda & Water",
      price: "1.25",
      description:
        "Choose from any of our soda or water options for a simple refreshment.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "not-coffee-10",
      categoryId: "not-coffee",
      name: "Cup Of Ice",
      price: "0.75",
      description:
        "Refreshing ice cubes, perfect for cooling your favorite beverages. Add to any iced drink for just 0.75.",
      page: "cafe",
      subpage: "menu",
    },

    {
      id: "food-0",
      categoryId: "food",
      name: "Melt",
      price: "9.25",
      description:
        "Classic chicken melts or meat-free options loaded with fresh veggies and zesty avocado lime sauce. Includes chips!",
      note: "Customize: Add bacon or extra cheese for +1.00.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-1",
      categoryId: "food",
      name: "3 Cheese Melt",
      price: "7.25",
      description:
        "Ultimate grilled cheese with provolone, mozzarella, and cheddar for a gooey, cheesy delight.",
      note: "Customize: Add tomato or ham for +1.00.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-2",
      categoryId: "food",
      name: "Bagel Sandwich",
      price: "5.50",
      description:
        "Our famous breakfast sandwich options on your choice of bagel, hearty and satisfying.",
      note: "Customize: Add cream cheese or sausage for +1.00.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-3",
      categoryId: "food",
      name: "Chips & Salsa",
      price: "5.25",
      description:
        "Our in-house made salsas with premium restaurant-style tortilla chips in a full bag.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-4",
      categoryId: "food",
      name: "Fruit Cup",
      price: "5.00",
      description: "Fresh-cut fruit, great for on-the-go refreshment.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-5",
      categoryId: "food",
      name: "Yogurt Parfait",
      price: "4.25",
      description:
        "Fresh-cut strawberries layered with our in-house baked granola and premium yogurt.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-6",
      categoryId: "food",
      name: "Burrito",
      price: "3.95",
      description:
        "1.5 ounces of fluffy in-house made eggs with cheese, wrapped and toasted in a tortilla.",
      note: "Customize: Add sausage or veggies for +1.00.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-7",
      categoryId: "food",
      name: "Bagel",
      price: "3.50",
      description:
        "Your choice of 3 different bagel types, best with a side of cream cheese.",
      note: "Customize: Add cream cheese for +1.00.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "food-8",
      categoryId: "food",
      name: "Pretzel Roll",
      price: "2.00",
      description:
        "Our famous in-house baked fresh pretzel rolls! Goes great with honey mustard or sour cream.",
      page: "cafe",
      subpage: "menu",
    },

    {
      id: "goods-0",
      categoryId: "goods",
      name: "Hot Cocoa Bomb",
      price: "13.00",
      description:
        "Chocolate sphere filled with cocoa powder—drop in hot milk and watch it explode into decadent delight! Perfect with any hot beverage.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "goods-1",
      categoryId: "goods",
      name: "Dipped Oreos",
      price: "7.50",
      description:
        "Oreo cookies dipped in various flavors of our in-house chocolate sauce for a crunchy, indulgent treat.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "goods-2",
      categoryId: "goods",
      name: "Peach Bar",
      price: "5.50",
      description:
        "Baked in-house peach bar with premium chopped freestone peaches and spiced crumble, juicy and crumbly.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "goods-3",
      categoryId: "goods",
      name: "Edible Cookie Dough",
      price: "5.00",
      description:
        "Carefully prepared, no-bake safe edible cookie dough that's soft and irresistible.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "goods-4",
      categoryId: "goods",
      name: "Scotcharoo",
      price: "4.00",
      description:
        "Crisp rice bar mixed with caramel and topped with our in-house dark and milk chocolate blend.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "goods-5",
      categoryId: "goods",
      name: "Muffin",
      price: "4.00",
      description:
        "Fan-favorite Cherry Walnut and other famous in-house muffins, moist and flavorful.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "goods-6",
      categoryId: "goods",
      name: "Brownie",
      price: "3.10",
      description:
        "Dense chocolate treat that will make you crave a glass of milk, fudgy and rich.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "goods-7",
      categoryId: "goods",
      name: "Cookies",
      price: "2.70",
      description:
        "Fresh-baked in-house cookies with options for everyone, including gluten-free—soft and chewy.",
      page: "cafe",
      subpage: "menu",
    },

    {
      id: "merch-0",
      categoryId: "merch",
      name: "Sweet Beans Tumbler",
      price: "25.00",
      description:
        "Reusable tumbler with secure lid and straw, ideal for on-the-go hydration. Limited stock!",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "merch-1",
      categoryId: "merch",
      name: "Sweet Beans Shirt",
      price: "20.00",
      description:
        "Comfortable shirt with our signature sweet beans design, made from soft, durable fabric.",
      page: "cafe",
      subpage: "menu",
    },

    {
      id: "catering-0",
      categoryId: "catering",
      name: "Breakfast Platter",
      price: "60.00",
      description:
        "Scrambled eggs, bacon, sausage links, sourdough toast, and tater tots. Order 24 hours in advance.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "catering-1",
      categoryId: "catering",
      name: "Pastry Platter",
      price: "55.00",
      description: "Assortment of croissants, pain au chocolat, and apple turnovers.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "catering-2",
      categoryId: "catering",
      name: "Panini Platter",
      price: "55.00",
      description:
        "Assorted panini with options: Chicken Pesto, Chicken Parmesan, Veggie Loaded.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "catering-3",
      categoryId: "catering",
      name: "Dessert Platter",
      price: "45.00",
      description:
        "Variety of chocolate chip cookies, double chocolate cookies, brownies, and muffins.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "catering-4",
      categoryId: "catering",
      name: "Turkey Sliders",
      price: "40.00",
      description:
        "Mini sandwiches with turkey, cheese, lettuce, tomato, pickles, and mayo.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "catering-5",
      categoryId: "catering",
      name: "Fruit/Veggie Platter",
      price: "35.00",
      description:
        "Vibrant assortment of fresh strawberries, pineapple, honeydew, cantaloupe, and red grapes.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "catering-6",
      categoryId: "catering",
      name: "Boxed Soup & Sandwich",
      price: "35.00",
      description:
        "Grilled cheese sandwich with cheddar on Texas toast paired with tomato bisque soup.",
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "catering-7",
      categoryId: "catering",
      name: "Pitcher Cold Brew",
      price: "20.00",
      description: "",
      page: "cafe",
      subpage: "menu",
    },

    {
      id: "bouquets-0",
      categoryId: "bouquets",
      name: "Sweet & Delicious",
      price: "50.99",
      description:
        "Fresh strawberries paired with chocolate-dipped strawberries, pineapple flowers, cantaloupe, etc. Upgrade your Dessert Platter with this for +40.00.",
      highlight: true,
      page: "cafe",
      subpage: "menu",
    },
    {
      id: "bouquets-1",
      categoryId: "bouquets",
      name: "Sweet Pineapple Treat",
      price: "38.25",
      description:
        "Heart-shaped pineapple slice surrounded by fresh strawberries, orange slices, and grapes.",
      page: "cafe",
      subpage: "menu",
    },
  ],
  wholesaleProducts: [
    {
      id: "BRZ-01",
      name: "Brazil Santos",
      origin: "Brazil",
      roast: "Medium",
      notes: "Caramel, toffee, mellow balance",
      acidity: "Low",
      use: "Espresso base, blends",
      sizes: "12oz, 2lb, 5lb",
      price: 61.0,
      image: "/sweetbeanswholesale/brazil.png",
      page: "wholesale",
      subpage: "catalog",
    },
    {
      id: "COL-01",
      name: "Colombia Supremo",
      origin: "Colombia",
      roast: "Medium",
      notes: "Chocolate, fruity, nutty",
      acidity: "Mellow",
      use: "Drip, medium roasts",
      sizes: "12oz, 2lb, 5lb",
      price: 65.0,
      image:
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=2070&auto=format&fit=crop",
      page: "wholesale",
      subpage: "catalog",
    },
    {
      id: "ETH-01",
      name: "Ethiopia Yirgacheffe",
      origin: "Ethiopia",
      roast: "Light",
      notes: "Citrus, floral, tropical fruits, jasmine",
      acidity: "Bright",
      use: "Pour-over, specialty",
      sizes: "12oz, 2lb, 5lb",
      price: 70.0,
      image: "/sweetbeanswholesale/ethiopia.png",
      page: "wholesale",
      subpage: "catalog",
    },
    {
      id: "GUA-01",
      name: "Guatemala Antigua",
      origin: "Guatemala",
      roast: "Medium",
      notes: "Chocolate, caramel, fruit hints",
      acidity: "Vibrant",
      use: "Bold drinks",
      sizes: "12oz, 2lb, 5lb",
      price: 66.0,
      image:
        "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1974&auto=format&fit=crop",
      page: "wholesale",
      subpage: "catalog",
    },
    {
      id: "SUM-01",
      name: "Sumatra Mandheling",
      origin: "Sumatra",
      roast: "Dark",
      notes: "Cedar, dark chocolate, cherries",
      acidity: "Low",
      use: "Dark roasts",
      sizes: "12oz, 2lb, 5lb",
      price: 63.5,
      image:
        "https://images.unsplash.com/photo-1559525839-b184a4d698c7?q=80&w=2070&auto=format&fit=crop",
      page: "wholesale",
      subpage: "catalog",
    },
    {
      id: "DEC-01",
      name: "Decaf Mexico",
      origin: "Mexico",
      roast: "Medium",
      notes: "Nutmeg, molasses, chocolate",
      acidity: "Tangy",
      use: "Decaf alternatives",
      sizes: "12oz, 2lb, 5lb",
      price: 67.5,
      image: "/sweetbeanswholesale/decaf-mexico.png",
      page: "wholesale",
      subpage: "catalog",
    },
  ],
  retailProducts: [
    {
      id: "RET-01",
      name: "Hampton House Blend",
      roast: "Medium",
      price: 21.5,
      image:
        "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=2070&auto=format&fit=crop",
      page: "shop",
      subpage: "retail",
    },
    {
      id: "RET-02",
      name: "Ethiopia Yirgacheffe",
      roast: "Light",
      price: 24.5,
      image:
        "https://img1.wsimg.com/isteam/ip/0815fdc9-aafc-4fe1-99f8-dedc9ba0e23b/1d77007d-8922-4127-bfdd-b6b332328c88.jpg",
      page: "shop",
      subpage: "retail",
    },
    {
      id: "RET-03",
      name: "Sumatra Dark",
      roast: "Dark",
      price: 21.5,
      image:
        "https://images.unsplash.com/photo-1559525839-b184a4d698c7?q=80&w=2070&auto=format&fit=crop",
      page: "shop",
      subpage: "retail",
    },
    {
      id: "RET-04",
      name: "Decaf Mexico",
      roast: "Medium",
      price: 23.0,
      image:
        "https://img1.wsimg.com/isteam/ip/0815fdc9-aafc-4fe1-99f8-dedc9ba0e23b/mexico_coffee.png",
      page: "shop",
      subpage: "retail",
    },
  ],
  siteAssets: [
    {
      id: "home-hero-image",
      page: "home",
      location: "hero-background-image",
      type: "image",
      url: "https://images.unsplash.com/photo-1743356629215-abb470447e71?q=80&w=2000&auto=format&fit=crop",
      alt: "Coffee Roasting Background",
    },
    {
      id: "home-hero-video",
      page: "home",
      location: "hero-background-iframe",
      type: "iframe",
      url: "https://player.vimeo.com/video/1157684253?background=1&autoplay=1&loop=1&byline=0&title=0",
    },
    {
      id: "home-card-wholesale",
      page: "home",
      location: "segment-card-wholesale",
      type: "image",
      url: "/sweetbeanswholesale/wholesale-coffee.png",
      alt: "Wholesale Coffee Bags",
      linkUrl: "/wholesale",
    },
    {
      id: "home-card-cafe",
      page: "home",
      location: "segment-card-cafe",
      type: "image",
      url: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2000&auto=format&fit=crop",
      alt: "Cafe Interior",
      linkUrl: "/cafe",
    },
    {
      id: "cafe-hero",
      page: "cafe",
      location: "hero-background",
      type: "image",
      url: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=2000&auto=format&fit=crop",
      alt: "Sweet Beans Cafe Interior",
    },
    {
      id: "wholesale-hero",
      page: "wholesale",
      location: "hero-background",
      type: "image",
      url: "/sweetbeanswholesale/wholesale-coffee.png",
      alt: "Wholesale Coffee",
    },
    {
      id: "wholesale-why-partner",
      page: "wholesale",
      location: "why-partner-image",
      type: "image",
      url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=1974&auto=format&fit=crop",
      alt: "Barista Training",
    },
    {
      id: "roastery-hero",
      page: "roastery",
      location: "hero-background",
      type: "image",
      url: "https://images.unsplash.com/photo-1561986810-4f3ba2f46ceb?q=80&w=2000&auto=format&fit=crop",
      alt: "Sweet Beans Roastery",
    },
    {
      id: "roastery-story-image",
      page: "roastery",
      location: "story-image",
      type: "image",
      url: "https://images.unsplash.com/photo-1515471897120-85416077e011?q=80&w=2000&auto=format&fit=crop",
      alt: "Roasting Process",
    },
    {
      id: "wholesale-partner-cafes",
      page: "wholesale",
      location: "partner-image-cafes",
      type: "image",
      url: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?q=80&w=800&auto=format&fit=crop",
      alt: "Partner Cafe",
    },
    {
      id: "wholesale-partner-restaurants",
      page: "wholesale",
      location: "partner-image-restaurants",
      type: "image",
      url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800&auto=format&fit=crop",
      alt: "Partner Restaurant",
    },
    {
      id: "wholesale-partner-offices",
      page: "wholesale",
      location: "partner-image-offices",
      type: "image",
      url: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop",
      alt: "Partner Office",
    },
    {
      id: "wholesale-partner-bakeries",
      page: "wholesale",
      location: "partner-image-bakeries",
      type: "image",
      url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop",
      alt: "Partner Bakery",
    },
    {
      id: "about-hero",
      page: "about",
      location: "hero-background",
      type: "image",
      url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=2070&auto=format&fit=crop",
      alt: "Coffee Community",
    },
    {
      id: "about-story-video",
      page: "about",
      location: "our-story-iframe",
      type: "iframe",
      url: "https://redir1.wavy.com/nxs-video/vid-anvato-3976575/embed/?autoplay=1&injected_via=embed&post_id=186929",
      alt: "Our Story Video",
    },
    {
      id: "about-veteran-owners",
      page: "about",
      location: "veteran-owners-image",
      type: "image",
      url: "/sweetbeanswholesale/veteran-owners.jpg",
      alt: "Mallory Rugg and Heather Amodeo - Veteran Owners of Sweet Beans",
    },
  ],
  homeFeaturedCoffees: [
    {
      id: "HFC-01",
      name: "Brazil",
      description: "Caramel, toffee, and a mellow balance. The perfect base for espresso or a smooth daily drip.",
      roast: "Medium",
      image: "https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?q=80&w=800&auto=format&fit=crop",
      fallbackImage: "/sweetbeanswholesale/brazil.png",
    },
    {
      id: "HFC-02",
      name: "Ethiopia Yirgacheffe",
      description: "Citrus, floral, and tropical fruits with jasmine notes. Bright and complex for pour-overs.",
      roast: "Light",
      image: "https://images.unsplash.com/photo-1611854779393-1b2a97063d83?q=80&w=800&auto=format&fit=crop",
      fallbackImage: "/sweetbeanswholesale/ethiopia.png",
    },
    {
      id: "HFC-03",
      name: "Decaf Mexico",
      description: "Swiss Water Process. Chocolate, cinnamon, and graham cracker. Smooth and caffeine-free.",
      roast: "Decaf",
      image: "https://images.unsplash.com/photo-1587049359689-a2a095536484?q=80&w=800&auto=format&fit=crop",
      fallbackImage: "/sweetbeanswholesale/decaf-mexico.png",
    },
  ],
}
